version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: voice-stack-postgres
    environment:
      POSTGRES_DB: synapse
      POSTGRES_USER: synapse
      POSTGRES_PASSWORD: synapse_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - core-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: voice-stack-redis
    volumes:
      - redis_data:/data
    networks:
      - core-network
    restart: unless-stopped

  synapse:
    image: matrixdotorg/synapse:latest
    container_name: voice-stack-synapse
    # Expose ports for direct access if needed (optional with Cloudflare)
    # ports:
    #   - "8008:8008"
    #   - "8448:8448"
    volumes:
      - ./synapse:/data
      - ./media_store:/media_store
    environment:
      SYNAPSE_SERVER_NAME: ${SERVER_NAME:-matrix.byte-box.org}
      SYNAPSE_REPORT_STATS: "no"
      SYNAPSE_CONFIG_PATH: /data/homeserver.yaml
    depends_on:
      - postgres
      - redis
    networks:
      - core-network
    restart: unless-stopped

  coturn:
    image: coturn/coturn:latest
    container_name: voice-stack-coturn
    # TURN server needs these ports for voice/video - cannot be proxied through Cloudflare
    ports:
      - "3478:3478/udp"
      - "3478:3478/tcp"
      - "5349:5349/udp"
      - "5349:5349/tcp"
      - "49152-49172:49152-49172/udp"
    volumes:
      - ./coturn/turnserver.conf:/etc/coturn/turnserver.conf:ro
    environment:
      TURN_USERNAME: ${TURN_USERNAME:-turn_user}
      TURN_PASSWORD: ${TURN_PASSWORD:-turn_password}
    networks:
      - core-network
    restart: unless-stopped

  element-web:
    image: vectorim/element-web:latest
    container_name: voice-stack-element
    # Port only needed for direct access (optional with Cloudflare)
    # ports:
    #   - "8080:80"
    volumes:
      - ./element/config.json:/app/config.json:ro
    depends_on:
      - synapse
    networks:
      - core-network
    restart: unless-stopped

networks:
  core-network:
    external: true

volumes:
  postgres_data:
  redis_data:
